
DROP VIEW localuse.vw_weblogdetails_2015_uber_live;


CREATE  VIEW localuse.vw_weblogdetails_2015_uber_live AS
 SELECT vw_realtime_data_latest.logdate,
        vw_realtime_data_latest.logtime,
        vw_realtime_data_latest.country_name,
        vw_realtime_data_latest.cs_uri_stem,
        vw_realtime_data_latest.page_type,
        vw_realtime_data_latest.site_section,
        vw_realtime_data_latest.article_id,
        vw_realtime_data_latest.iwork_wk,
        vw_realtime_data_latest.cweek_day,
        lead(vw_realtime_data_latest.article_id, 1, '0'::varchar(255)) OVER (PARTITION BY vw_realtime_data_latest.visitor_id, vw_realtime_data_latest.logdate ORDER BY vw_realtime_data_latest.logdate, vw_realtime_data_latest.logtime) AS next_article_id,
        CASE WHEN (vw_realtime_data_latest.referer_page_type IS NOT NULL) THEN vw_realtime_data_latest.referer_page_type WHEN (vw_realtime_data_latest.referer_host IS NOT NULL) THEN vw_realtime_data_latest.referer_host WHEN ((vw_realtime_data_latest.referer_page_type IS NULL) AND (vw_realtime_data_latest.referer_host IS NULL) AND (vw_realtime_data_latest.cs_cookies ~~* '%utmcsr%'::varchar(8)) AND ((instr(vw_realtime_data_latest.cs_cookies, '|utmccn='::varchar(8), 1, 1) - instr(vw_realtime_data_latest.cs_cookies, '.utmcsr='::varchar(8), 1, 1)) >= 0)) THEN ltrim(ltrim(rtrim(substr(substr(vw_realtime_data_latest.cs_cookies, 1, (instr(vw_realtime_data_latest.cs_cookies, '.utmcsr='::varchar(8), 1, 1) + (instr(vw_realtime_data_latest.cs_cookies, '|utmccn='::varchar(8), 1, 1) - instr(vw_realtime_data_latest.cs_cookies, '.utmcsr='::varchar(8), 1, 1)))), ((length(substr(vw_realtime_data_latest.cs_cookies, 1, (instr(vw_realtime_data_latest.cs_cookies, '.utmcsr='::varchar(8), 1, 1) + (instr(vw_realtime_data_latest.cs_cookies, '|utmccn='::varchar(8), 1, 1) - instr(vw_realtime_data_latest.cs_cookies, '.utmcsr='::varchar(8), 1, 1))))) - (instr(vw_realtime_data_latest.cs_cookies, '|utmccn='::varchar(8), 1, 1) - instr(vw_realtime_data_latest.cs_cookies, '.utmcsr='::varchar(8), 1, 1))) + 1), (instr(vw_realtime_data_latest.cs_cookies, '|utmccn='::varchar(8), 1, 1) - instr(vw_realtime_data_latest.cs_cookies, '.utmcsr='::varchar(8), 1, 1))), '|'::varchar(1)), 'utmscr'::varchar(6)), '='::varchar(1)) ELSE 'unknown'::varchar(7) END AS referer_page_type,
        CASE WHEN ((vw_realtime_data_latest.cs_cookies ~~* '%IT_UUID='::varchar(9)) AND (vw_realtime_data_latest.visitor_id IS NOT NULL)) THEN vw_realtime_data_latest.visitor_id WHEN ((vw_realtime_data_latest.cs_cookies ~~* '%IT_UUID='::varchar(9)) AND (vw_realtime_data_latest.mpp_account_id IS NOT NULL)) THEN vw_realtime_data_latest.mpp_account_id WHEN ((vw_realtime_data_latest.cs_cookies ~~* '%IT_UUID='::varchar(9)) AND ("char_length"(vw_realtime_data_latest.cs_cookies) = 2000) AND (vw_realtime_data_latest.mpp_account_id IS NULL) AND (vw_realtime_data_latest.visitor_id IS NULL)) THEN (concat((vw_realtime_data_latest.logdate)::varchar, vw_realtime_data_latest.logtime) || vw_realtime_data_latest.article_id) WHEN (vw_realtime_data_latest.cs_cookies ~~* '%IT_UUID=%'::varchar(10)) THEN "substring"(vw_realtime_data_latest.cs_cookies, regexp_instr(vw_realtime_data_latest.cs_cookies, 'IT_UUID='::varchar(8), 1, 1, 1, ''::varchar, 0), 36) WHEN ((vw_realtime_data_latest.cs_cookies !~~* '%IT_UUID=%'::varchar(10)) AND (vw_realtime_data_latest.visitor_id IS NOT NULL)) THEN vw_realtime_data_latest.visitor_id WHEN ((vw_realtime_data_latest.cs_cookies !~~* '%IT_UUID=%'::varchar(10)) AND (vw_realtime_data_latest.mpp_account_id IS NOT NULL)) THEN vw_realtime_data_latest.mpp_account_id WHEN ((vw_realtime_data_latest.cs_cookies = ANY (ARRAY['undefined'::varchar(9), 'IT_cookiepopup=1'::varchar(16)])) AND (vw_realtime_data_latest.visitor_id IS NOT NULL)) THEN vw_realtime_data_latest.visitor_id WHEN ((vw_realtime_data_latest.cs_cookies = ANY (ARRAY['undefined'::varchar(9), 'IT_cookiepopup=1'::varchar(16)])) AND (vw_realtime_data_latest.mpp_account_id IS NOT NULL)) THEN vw_realtime_data_latest.mpp_account_id WHEN (vw_realtime_data_latest.cs_cookies !~~* '%_cb_ls=1%'::varchar(10)) THEN vw_realtime_data_latest.cs_cookies WHEN (vw_realtime_data_latest.cs_cookies ~~* '__utmc=%'::varchar(8)) THEN vw_realtime_data_latest.cs_cookies ELSE NULL END AS visitor_id,
        CASE WHEN (vw_realtime_data_latest.unique_id IS NULL) THEN vw_realtime_data_latest.mpp_account_id ELSE vw_realtime_data_latest.unique_id END AS unique_id,
        CASE WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Windows+NT%'::varchar(12)) THEN 'Windows'::varchar(7) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%iPad%'::varchar(6)) THEN 'IOS'::varchar(3) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Macintosh%'::varchar(11)) THEN 'IOS'::varchar(3) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%iPhone%'::varchar(8)) THEN 'IOS'::varchar(3) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Android%'::varchar(9)) THEN 'Android'::varchar(7) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Apple-PubSub%'::varchar(14)) THEN 'IOS'::varchar(3) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%CrOS%'::varchar(6)) THEN 'Chrome OS'::varchar(9) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Ubuntu%'::varchar(8)) THEN 'Ubuntu Linux'::varchar(12) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Windows+Phone%'::varchar(15)) THEN 'Windows'::varchar(7) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%iPod%'::varchar(6)) THEN 'IOS'::varchar(3) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%BB10%'::varchar(6)) THEN 'Blackberry'::varchar(10) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Darwin%'::varchar(8)) THEN 'Darwin'::varchar(6) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Linux%'::varchar(7)) THEN 'Linux'::varchar(5) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Blackberry%'::varchar(12)) THEN 'Blackberry'::varchar(10) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Opera+Mini%'::varchar(12)) THEN 'unknown mobile'::varchar(14) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%PlayBook%'::varchar(10)) THEN 'Blackberry'::varchar(10) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%AppleSyndication%'::varchar(18)) THEN 'IOS'::varchar(3) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Playstation%'::varchar(13)) THEN 'Playstation'::varchar(11) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Nintendo%'::varchar(10)) THEN 'Nintendo'::varchar(8) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Opera Mini%'::varchar(12)) THEN 'unknown mobile'::varchar(14) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Google Wireless Transcoder%'::varchar(28)) THEN 'unknown mobile'::varchar(14) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Windows NT%'::varchar(12)) THEN 'Windows'::varchar(7) ELSE 'unknown'::varchar(7) END AS OS,
        vw_realtime_data_latest.referer_site_section,
        vw_realtime_data_latest.referer_articleid,
        vw_realtime_data_latest.mpp_account_id,
        vw_realtime_data_latest.unique_id as visitor,
        CASE WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Windows+NT%'::varchar(12)) THEN 'Desktop'::varchar(7) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%iPad%'::varchar(6)) THEN 'Tablet'::varchar(6) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Macintosh%'::varchar(11)) THEN 'Desktop'::varchar(7) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%iPhone%'::varchar(8)) THEN 'Mobile'::varchar(6) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%X11;+Linux%'::varchar(12)) THEN 'Desktop'::varchar(7) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Android%mobile%'::varchar(16)) THEN 'Mobile'::varchar(6) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Android%'::varchar(9)) THEN 'Tablet'::varchar(6) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Apple-PubSub%'::varchar(14)) THEN 'Desktop'::varchar(7) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%CrOS%'::varchar(6)) THEN 'Desktop'::varchar(7) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Ubuntu%'::varchar(8)) THEN 'Desktop'::varchar(7) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Windows+Phone%'::varchar(15)) THEN 'Mobile'::varchar(6) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%iPod%'::varchar(6)) THEN 'Mobile'::varchar(6) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%BB10%'::varchar(6)) THEN 'Mobile'::varchar(6) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Darwin%'::varchar(8)) THEN 'Desktop'::varchar(7) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Linux%'::varchar(7)) THEN 'Desktop'::varchar(7) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Desktop%'::varchar(9)) THEN 'Desktop'::varchar(7) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Blackberry%'::varchar(12)) THEN 'Mobile'::varchar(6) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Opera+Mini%'::varchar(12)) THEN 'Mobile'::varchar(6) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Tablet%'::varchar(8)) THEN 'Tablet'::varchar(6) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%AppleSyndication%'::varchar(18)) THEN 'Desktop'::varchar(7) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Playstation%'::varchar(13)) THEN 'Desktop'::varchar(7) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Nintendo+Wii%'::varchar(14)) THEN 'Mobile'::varchar(6) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Nintendo%'::varchar(10)) THEN 'Desktop'::varchar(7) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Mobile%'::varchar(8)) THEN 'Mobile'::varchar(6) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Windows NT%'::varchar(12)) THEN 'Desktop'::varchar(7) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Opera Mini%'::varchar(12)) THEN 'Mobile'::varchar(6) WHEN (vw_realtime_data_latest.cs_user_agent ~~* '%Google Wireless Transcoder%'::varchar(28)) THEN 'Mobile'::varchar(6) ELSE 'unknown'::varchar(7) END AS device,
        vw_realtime_data_latest.user_type
 FROM datalayer.vw_realtime_data_latest
 WHERE (vw_realtime_data_latest.cs_user_agent !~~* '%Googlebot%'::varchar(11));

SELECT MARK_DESIGN_KSAFE(0);
